config/routes.rb
Rails.application.routes.draw do
  root  "posts#index"
  resources :posts do
    collection do
      post :confirm
    end
  end
  resources :products do
    collection do
      post :confirm
    end
  end
  resources :users, only: [:new, :create, :edit, :update, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :favorites, only: [:create, :destroy]
  mount LetterOpenerWeb::Engine, at: '/inbox' if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :user
    has_many :favorites, dependent: :destroy
    has_many :favorites_users, through: :favorites, source: :user
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence:true, length: {minimum:3, maximum:30}
    validates :email, presence:true, length: { maximum:255 }, 
                format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i},
                uniqueness: true        
    has_secure_password
    validates :password, presence: true, length: { minimum:8 }, unless: Proc.new { |user| user.password.blank? }
    mount_uploader :image, ImageUploader
    has_many :posts
    has_many :products
    has_many :favorites, dependent: :destroy
    has_many :favorites_posts, through: :favorites, source: :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionsHelper
    before_action :login_required
    private
    def login_required
        redirect_to new_session_path unless current_user
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(post_id: params[:post_id])
    redirect_to posts_path, notice: "You add #{favorite.post.user.name} post to your favorites posts"
  end
  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to posts_path, notice: "You delete #{favorite.post.user.name} post to your favorites posts"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit,:update,:destroy]
  def index
    @posts = Post.all.order(updated_at: :desc)
  end
  def new
    @post = Post.new
  end
  def create
    @post = current_user.posts.build(post_params)
    if params[:back]
        render :new
    else
        if @post.save
          redirect_to posts_path, notice: "New post created"
        else
          render :new
        end
    end
  end
  def confirm
    @post = current_user.posts.build(post_params)
    render :new if @post.invalid?
  end
  def show
    @favorite = current_user.favorites.find_by(post_id: @post.id)
  end
  def edit
  end
  def update
    if @post.update(post_params)
      redirect_to posts_path, notice: "Post update with success"
    else
      render :edit
    end
  end
  def destroy
    @post.destroy
    redirect_to posts_path, notice: "Post delete with success"
  end
  private
  def post_params
    params.require(:post).permit(:content, :image, :image_cache)
  end
  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :set_product, only: [:edit, :update, :show, :destroy]
    def index
        @products = Product.all.order(created_at: :desc)
    end
    def new
        @product = Product.new
    end
    def create
        @product = current_user.products.build(product_params)
        if params[:back]
            render :new
        else
            if @product.save
                redirect_to products_path, notice: "New product create with success. This is my first pull request."
            else
                render :new
            end
        end
    end
    def confirm
        @product = current_user.products.build(product_params)
        render :new if @product.invalid?
    end
    def edit
    end
    def show
    end
    def update
        if @product.update(product_params)
            redirect_to products_path, notice: "Product update with success"
        else
            render :edit
        end
    end
    def destroy
        @product.destroy
        redirect_to products_path, notice: "Product delete with success"
    end


    private
    def product_params
        params.require(:product).permit(:title, :price, :image, :image_cache)
    end
    def set_product
        @product = Product.find(params[:id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id]= user.id
      redirect_to posts_path, notice: "Happy to see you again #{user.name}"
    else
      flash.now[:danger] = "Please enter correct login details."
      render :new
    end
  end
  def destroy
    session.delete(:user_id)
    redirect_to new_session_path, notice: "Logout success"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  before_action :set_user, only: [:show,:edit,:update]
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_session_path, notice: "Welcome #{@user.name}"
    else  
      render :new
    end
  end
  def show
    if current_user.id != @user.id
      render :file => "#{Rails.root}/public/404.html",  layout: false, status: :not_found
    end
  end
  def edit
  end
  def update
    if @user.update(user_params)
      redirect_to user_path, notice: "Update informations with success"
    else
      render :edit
    end
  end
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :image_cache)
  end
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    def choose_new_or_edit
        if action_name == 'new' || action_name == 'create'
            confirm_posts_path
        elsif action_name == 'edit'
            post_path    
        end
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    def logged_in?
        current_user.present?
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstaApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-light">
      <% if logged_in? %>
        <nav class="navbar navbar-expand-lg navbar-light bg-white sticky-top pt-0 pb-0">
          <a class="navbar-brand m-0" href="/posts">
            <%= image_tag "logo.png", height: 52, width:130 %>
          </a>
          <button class="navbar-toggler border-0" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon text-dark"></span>
          </button>  
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item dropdown pr-5">
                <a class="nav-link dropdown-toggle font-weight-bold pr-3" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <%= current_user.name %> 
                </a>
                <div class="dropdown-menu shadow mb-5 bg-white rounded border-0" aria-labelledby="navbarDropdown">
                  <%= link_to 'Create new Post', new_post_path, class: "p-3" %>
                  <div class="dropdown-divider"></div>
                  <%= link_to 'Profile', user_path(current_user.id), class: "dropdown-item text-center font-weight-bold" %>                 
                  <%= link_to 'Logout', session_path(current_user.id), method: :delete, class: "dropdown-item text-center font-weight-bold" %>
                </div>
              </li>
            </ul>
          </div>
        </nav> 
      <% end %>
      <% flash.each do |key, value| %>
        <%= content_tag(:div, class: "alert alert-#{key} alert-dismissible fade show pt-2 pb-2", role: "alert") do %>
          <p class="text-center font-weight-bold"><%= value %> </p>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        <% end %>  
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class= "container">
    <div class= "row justify-content-center align-content-center">
        <div class="col-md-7 text-center">
            <div class="card shadow mb-5 p-4 bg-white border-0 index-card" >
                <%= form_with(model: @post, local:true, url:choose_new_or_edit) do |form| %>
                    <% if @post.errors.any? %>
                    <div id= "error_explanation">
                        <% @post.errors.full_messages.each do |msg|%>
                            <p class = "error"><%= msg %></p>
                        <%end%>
                    </div>
                    <%end%>
                    <div class= "post_image mb-3"> 
                        <%= image_tag(@post.image.url) if @post.image && @post.image.url %>
                    </div>
                    <div class= "form-group">
                        <%= form.text_area :content, class: "form-control", placeholder: "Says something", rows: 10 %>
                    </div>
                    <div class= "form-group mt-3">
                        <%= form.file_field :image %>
                        <%= form.hidden_field :image_cache %>
                    </div>
                    <%= form.submit "Post", class: "btn btn-primary font-weight-bold text-uppercase mt-3 pl-3 pr-3 pt-2 pb-2"%>
                <%end%>
            </div>   
        </div>
    </div>
</div>

app/views/posts/confirm.html.erb
<h3 class="mt-3 text-center mb-3">Confirm informations</h1>
<div class= "container mt-5">
    <div class= "row justify-content-center align-content-center">
        <div class="col-md-7 text-center">
            <div class="card shadow mb-5 p-4 bg-white border-0 index-card" >
                <%= form_with(model: @post, local:true) do |form| %>
                    <%= form.hidden_field :image_cache %> 
                    <%= form.hidden_field :content %>
                    <% if @post.content != "" %>
                    <p class= "text-justify"><%= @post.content %></p> 
                    <%end%>
                    <div class= "post_image mb-4"> 
                        <%= image_tag(@post.image.url) if @post.image && @post.image.url %>
                    </div>
                    <%= form.submit "Post", class: "btn btn-success mr-3 text-white font-weight-bold pt-2 pb-2 pl-3 pr-3" %>
                    <%= form.submit "Return to edit", name: 'back', class: "btn btn-danger font-weight-bold pt-2 pb-2 pl-3 pr-3" %>
                <%end%>
            </div>
        </div>
    </div>
</div>

app/views/posts/edit.html.erb
<h3 class="mt-3 text-center mb-3">Edit post</h1>
<%= render 'form' %>

app/views/posts/index.html.erb
<div class="container-fluid mt-5">
    <div class="row justify-content-around align-content-center ">
        <div class= "col-lg-5 col-md-8">
            <div class="row justify-content-center align-content-center ">
                <% @posts.each do |post| %>
                    <div class= "col-md-12 pl-5 pr-5">
                        <div class="card mb-5 bg-white" >
                            <div class="card-header pl-4 pb-0" style="border: none; background-color:white;">
                                <div class="row justify-content-between align-content-center">
                                    <div class= "col-md-4 pl-3 pr-3">
                                        <% if post.user.image && post.user.image.url%>
                                            <%= image_tag (post.user.image.url), class: "rounded-circle" %> <span class="pl-2 font-weight-bold" style="font-size: 16px; color:#364D59;"><%= post.user.name %></span>
                                        <%else%>
                                            <%= image_tag "default.png", width: 100, class: "rounded-circle" %> <span class="pl-2 font-weight-bold" style="font-size: 16px; color:#364D59;"><%= post.user.name %></span>
                                        <% end %>
                                    </div>
                                    <div class= "col-md-6 pt-4">
                                        <ul class="nav justify-content-end ">
                                            <li class="nav-item pr-3 ">
                                                <%= link_to  'Details' , post_path(post.id), class: "card-menu-link"   %>
                                            </li>
                                            <% if post.user_id == current_user.id %>
                                                <li class="nav-item pr-3 ">
                                                    <%= link_to  'Edit' , edit_post_path(post.id), class: "card-menu-link"  %>
                                                </li>
                                                <li><%= link_to  'Delete' , post_path(post.id), method: :delete , data: { confirm: 'Are you sure to delete'}, class: "card-menu-link" %></li>
                                            <% end %>   
                                        </ul> 
                                    </div>
                                </div> 
                            </div>                           
                            <div class="card-body p-0 mt-3">
                                <div class="text-center">
                                    <%= image_tag (post.image.url), class: "post-img" %>
                                    <% unless current_user.id == post.user.id %>
                                        <% if current_user.favorites.find_by(post_id: post.id).present?%>
                                            <%= link_to favorite_path(current_user.favorites.find_by(post_id: post.id).id),  method: :delete do%>
                                                <p class= "mt-3"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" width="40" height="40" preserveAspectRatio="xMidYMid meet" viewBox="0 0 1024 1024"><path d="M923 283.6a260.04 260.04 0 0 0-56.9-82.8a264.4 264.4 0 0 0-84-55.5A265.34 265.34 0 0 0 679.7 125c-49.3 0-97.4 13.5-139.2 39c-10 6.1-19.5 12.8-28.5 20.1c-9-7.3-18.5-14-28.5-20.1c-41.8-25.5-89.9-39-139.2-39c-35.5 0-69.9 6.8-102.4 20.3c-31.4 13-59.7 31.7-84 55.5a258.44 258.44 0 0 0-56.9 82.8c-13.9 32.3-21 66.6-21 101.9c0 33.3 6.8 68 20.3 103.3c11.3 29.5 27.5 60.1 48.2 91c32.8 48.9 77.9 99.9 133.9 151.6c92.8 85.7 184.7 144.9 188.6 147.3l23.7 15.2c10.5 6.7 24 6.7 34.5 0l23.7-15.2c3.9-2.5 95.7-61.6 188.6-147.3c56-51.7 101.1-102.7 133.9-151.6c20.7-30.9 37-61.5 48.2-91c13.5-35.3 20.3-70 20.3-103.3c.1-35.3-7-69.6-20.9-101.9z" fill="red"/></svg></p>
                                                
                                            <% end %>
                                            
                                        <%else%>
                                            <%= link_to favorites_path(post_id: post.id),  method: :post do%>
                                                <p class= "mt-3"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" width="40" height="40" preserveAspectRatio="xMidYMid meet" viewBox="0 0 16 16"><g fill="currentColor"><path d="M8 2.748l-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385c.92 1.815 2.834 3.989 6.286 6.357c3.452-2.368 5.365-4.542 6.286-6.357c.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/></g></svg></p>
                                            <% end %>
                                        <% end %>
                                    <% end %>
                                    <p class="text-justify pl-3 mt-3">
                                    <span class=" font-weight-bold" style="font-size: 16px; color:#364D59;"><%= post.user.name %>
                                    <% if post.content != "" %>
                                        <span class="font-weight-normal pl-3"><%= post.content %></span>
                                    <% end %>
                                    </p>
                                    <p class= "text-capitalize small text-justify pl-3"><%= time_ago_in_words(post.created_at) %></p>
                                </div>
                            </div>  
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>


app/views/posts/new.html.erb
<h3 class= "mb-4 text-center mt-4">Add new post</h3>
<%= render 'form' %>

app/views/posts/show.html.erb
<h3 class="mt-3 text-center mb-3">Post details</h3>
<div class= "container mt-5">
  <div class= "row justify-content-center align-content-center">
    <div class="col-md-7 text-center">
      <div class="card shadow mb-5 pt-3 bg-white border-0 index-card" >
        <% if @post.content != "" %>
        <p class= "text-justify pl-4"><%= @post.content %></p> 
        <%end%>
        <div class= "post_image mb-4"> 
            <%= image_tag(@post.image.url) %>
        </div> 
        <div class="card-header pl-4 pb-0">
          <ul class="nav justify-content-center">
            <% if @post.user_id == current_user.id %>
              <li class="nav-item mr-4">
                <%= link_to 'Edit', edit_post_path(@post) %>
              </li>
            <% else %>
                <% if @favorite.present? %>
                    <%= link_to 'Delete Favorite', favorite_path(@favorite.id), method: :delete, class: 'btn btn-danger'%>
                <% else %>
                    <p><%= link_to 'Add to favorite', favorites_path(post_id: @post.id), method: :post, class: 'btn btn-primary' %></p>
                <% end %>
            <% end %>
            <li class="nav-item">
              <%= link_to 'Back', posts_path %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="container mt-5">
    <div class="row justify-content-around align-content-center ">
        <div class= "col-lg-3 col-md-5">
            <div class="row justify-content-center align-content-center ">
            <% if @products.count > 0  %>
                <% @products.each do |product| %>
                    <div class= "col-md-12 pl-5 pr-5">
                        <div class="card mb-5 bg-white" >
                            <div class="card-header pl-4 pb-0" style="border: none; background-color:white;">
                                <div class="row justify-content-between align-content-center">
                                    <div class= "col-md-4 pl-3 pr-3">
                                        <% if product.user.image && product.user.image.url%>
                                            <%= image_tag (product.user.image.url), class: "rounded-circle" %> <span class="pl-2 font-weight-bold" style="font-size: 16px; color:#364D59;"><%= product.user.name %></span>
                                        <%else%>
                                            <%= image_tag "default.png", width: 100, class: "rounded-circle" %> <span class="pl-2 font-weight-bold" style="font-size: 16px; color:#364D59;"><%= product.user.name %></span>
                                        <% end %>
                                    </div>
                                    <div class= "col-md-6 pt-4">
                                        <ul class="nav justify-content-end ">
                                            <li class="nav-item pr-3 ">
                                                <%= link_to  'Details' , product_path(product.id), class: "card-menu-link"   %>
                                            </li>
                                            <% if product.user_id == current_user.id %>
                                                <li class="nav-item pr-3 ">
                                                    <%= link_to  'Edit' , edit_product_path(product.id), class: "card-menu-link"  %>
                                                </li>
                                                <li><%= link_to  'Delete' , product_path(product.id), method: :delete , data: { confirm: 'Are you sure to delete'}, class: "card-menu-link" %></li>
                                            <% end %>   
                                        </ul> 
                                    </div>
                                </div> 
                            </div>                           
                            <div class="card-body p-0 mt-3">
                                <div class="text-center">
                                    <%= image_tag (product.image.url), class: "product-img" %>
                                    
                                    <p class="text-justify pl-3 mt-3">
                                    <span class=" font-weight-bold" style="font-size: 16px; color:#364D59;"><%= product.user.name %>
                                    <% if product.content != "" %>
                                        <span class="font-weight-normal pl-3"><%= product.content %></span>
                                    <% end %>
                                    </p>
                                    <p class= "text-capitalize small text-justify pl-3"><%= time_ago_in_words(product.created_at) %></p>
                                </div>
                            </div>  
                        </div>
                    </div>
                <% end %>
            <%else%>
                <h1> Aucun produit ajouté actuellement</h1>
            <% end %>
            </div>
        </div>
    </div>
</div>


app/views/users/edit.html.erb
<% if @user.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show pt-2 pb-2 text-center">
        
        <% @user.errors.full_messages.each do |msg| %>
            <p><%= msg %></p>
        <% end %>
        
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<% end %>
<div class="container mt-5">
    <div class="row justify-content-center align-content-center mt-5 ">
        <div class= "col-md-8">
            <div class="card p-3 mb-3 bg-white" >
                <div class="card-body">
                <div class=" row justify-content-center">
                    <div class= "col-md-8">
                        <div class="profile-img text-center">
                            <% if @user.image && @user.image.url%>
                                <%= image_tag (@user.image.url), id: "user-avatar" %>
                            <%else%>
                                <%= image_tag "default.png", width: 100, class: "rounded-circle", id: "user-avatar" %> 
                            <% end %>
                            <p class="text-downcase semi-info font-weight-bold mt-2"><%= @user.name %></p>
                        </div>
                        <%= form_with(model: @user, local: true) do |form| %>
                        <div class= "form-group mt-3 text-center image-text">
                            <%= form.label :image ,"Edit profile photo"%>
                            <%= form.file_field :image, class: "input-image", onchange: "document.getElementById('user-avatar').src = window.URL.createObjectURL(this.files[0])" %>
                            <%= form.hidden_field :image_cache %>
                        </div>
                        <div class="form-group">
                            <%= form.label :name %><%= form.text_field :name, class: "form-control"%>
                        </div>
                        <div class="form-group">
                            <%= form.label :email %><%= form.text_field :email, class: "form-control"%>
                        </div>
                        <div class="row justify-content-center mb-3 mt-5">
                            <div class="col-md-12 text-center">
                                <%= form.submit "Save Profile", class:"btn btn-primary font-weight-bold pl-5 pr-5" %>
                            </div>
                        </div>                         
                    <% end %>
                    </div>
                </div>               
                </div>  
            </div>
        </div> 
    </div>
</div>

app/views/users/new.html.erb
<% if @user.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show pt-2 pb-2 text-center">
        <% @user.errors.full_messages.each do |msg| %>
            <p><%= msg %></p>
        <% end %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<% end %>
<div class="container mt-5">
    <div class="row justify-content-center align-content-center pt-5 mt-5 ">
        <div class= "col-lg-5 col-md-8 col-sm-12 col-xl-4">
            <div class="card p-3 mb-3 bg-white" >
                <div class="card-header pl-4 pb-0 text-center" style="border: none; background-color:white;">
                    <%= image_tag "logo.png" %>   
                    <p class="mt-2 font-weight-bold semi-info">Sign up to see your friends photos and videos.</p>       
                </div>
                <div class="card-body">
                    <%= form_with(model: @user, local: true) do |form| %>
                        <div class="form-group">
                            <%= form.text_field :email, class: "form-control bg-light small", required: true, placeholder: "Email address" %>
                        </div>
                        <div class="form-group">
                            <%= form.text_field :name, class: "form-control bg-light", required: true, placeholder: "Name" %>
                        </div>
                        
                        <div class="form-group">
                            <%= form.password_field :password, class: "form-control bg-light", required: true, placeholder: "Password" %>
                        </div>
                        <div class="form-group">
                            <%= form.password_field :password_confirmation, class: "form-control bg-light", required: true, placeholder: "Confirm password" %>
                        </div>
                        <div class="row justify-content-center mb-3 mt-4">
                            <div class="col-md-12 text-center">
                                <%= form.submit "Create Account", class:"btn btn-primary font-weight-bold pl-5 pr-5" %>
                            </div>
                        </div>
                        <p class="semi-info small text-center m-0 ">By registering, you agree to our <span class="font-weight-bold">Terms and Conditions</span> , our <span class="font-weight-bold">Data Policy</span> and our <span class="font-weight-bold">Cookie Policy.</span></p>                         
                    <% end %>
                </div>  
            </div>
            <div class="card bg-white" >
                <div class="card-body  pb-4 pt-4">
                    <p class="small text-center m-0 ">Do you have an account ? <%= link_to 'Sign in', new_session_path, class:"" %></p> 
                </div>      
            </div>
        </div> 
    </div>
</div>

app/views/users/show.html.erb
<div class= "container mt-5">
    <div class="row justify-content-center align-content-center">
        <div class="col-md-10 text-center">
            <div class="profile-img">
                <% if @user.image && @user.image.url%>
                    <%= image_tag(@user.image.url)%>
                <%else%>
                    <%= image_tag "default.png", width: 100, class: "rounded-circle" %> 
                <% end %>
            </div>
            <p class="text-downcase semi-info font-weight-bold mt-2"><%= @user.name %></p>
            <p class="text-downcase text-dark font-weight-bold mt-3"><%= @user.posts.count %> Post(s) <span class="ml-3"> <%= @user.favorites.count %> Favorites Post(s) <%= link_to  'Edit profile', edit_user_path(@user.id), class: "edit-link ml-3"%><span> </p>
        <div class="dropdown-divider mt-5"></div>
        </div>
    </div>
    <div class="row justify-content-center align-content-center mt-3">
        <div class="col-md-10 text-center">
            <ul class="tab nav justify-content-center">
                <li class="select nav-item">Posts</li>
                <li class="nav-item">Favorites Posts</li>
            </ul>           
            <div class="content mt-4">
                <div class="list-posts row justify-content-center">  
                    <% @user.posts.each do |post|%>
                        <div class= "col-md-4">
                            <%= image_tag(post.image.url) %>
                        </div>                        
                    <% end %>
                </div>
                <div class=" list-posts hide row justify-content-center">
                    <% @user.favorites_posts.each do |post|%>
                        <div class= "col-md-4">
                            <%= image_tag(post.image.url)%>
                        </div>
                    <% end %>                   
                </div>
            </div>            
        </div>
    </div>    
</div>
<script>
    $(function(){
    $('.tab li').on('click',function(){
        $('.tab li').removeClass('select');
        $(this).addClass('select');
        $('.content .list-posts').addClass('hide');
        let index = $('.tab li').index($(this))
        $('.content .list-posts').eq(index).removeClass('hide')
    });
});
</script>